Add "CompositeMonoInstaller" and "CompositeScriptableObjectInstaller"
modesttree/Zenject pull request #211
Opened 2021-02-05 13:30 UTC by tsgcpp

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] No compiler errors or warnings

## Pull request type

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Issue Number

Issue Number: N/A

*Create or search an issue here: [Extenject/Issues](https://github.com/svermeulen/Extenject/issues)*

## What is the current behavior?

- No changes against current behaviours

## What is the new behavior?

- Add "CompositeMonoInstaller" and "CompositeScriptableObjectInstaller" to "OptionalExtras". They are the composite pattern of Extenject installers
- Add a document about them named "CompositeInstaller.md", so I wonder if you could also read the md file
- Add tests for "CompositeMonoInstaller" and "CompositeScriptableObjectInstaller"
  - All asset files and prefabs are for the tests.
- Add editor scripts for "CompositeMonoInstaller" and "CompositeScriptableObjectInstaller" to warn circular references if any circular references are found in the installers

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- You can see the components looks in "CompositeInstaller.md"

On which Unity version has this been tested?
--------------------------------------------
- [ ] 2020.4 LTS
- [ ] 2020.3
- [x] 2020.2
- [ ] 2020.1
- [x] 2019.4 LTS
- [ ] 2019.3
- [ ] 2019.2
- [ ] 2019.1
- [ ] 2018.4 LTS

**Scripting backend:**
- [x] Mono
- [x] IL2CPP

2021-02-05 15:21 UTC, Mathijs-Bakker commented
@tsgcpp This is an awesome feature!
It's a lot to review, so it could take some days.
I like the tooling you've done and the circular dependency warning.

Great work!

2021-02-06 19:45 UTC, Mathijs-Bakker commented on UnityProject/Assets/Plugins/Zenject/OptionalExtras/CompositeInstaller/Tests/IntegrationTests/Install/TestCompositeMonoInstaller/FooInjectee.cs
> +    public class FooInjectee
Sorry, but could this be a typo? Did you mean FooInjector.cs?

2021-02-06 19:49 UTC, Mathijs-Bakker commented on UnityProject/Assets/Plugins/Zenject/OptionalExtras/CompositeInstaller/Tests/IntegrationTests/Install/TestCompositeMonoInstaller/FooInjectee.cs
> +    public class FooInjectee
My bad... this is perfect grammar X)

2021-02-06 20:08 UTC, Mathijs-Bakker approved these changes
Well written clean code and tests!

2021-02-06 20:43 UTC, Mathijs-Bakker commented
@tsgcpp This feature is a great addition to Zenject. 
I can merge your pr as submitted. Which means your feature will be in 'Optional Extras',
But it deserves to be standard functionality, so we could move it into into Zenject/source/...
What about it? Merge (for now) or move to the core?

2021-02-07 05:52 UTC, tsgcpp commented
@Mathijs-Bakker I really appreciate your review and your suggestion.

> But it deserves to be standard functionality, so we could move it into into Zenject/source/...
What about it? Merge (for now) or move to the core?

If there is no problem, I would like to move them into "Zenject/source/...".
Would you tell me where to move them?

Is it ok to move them like this?
- https://github.com/tsgcpp/Extenject/compare/feature/composite-installer...tsgcpp:wip/feature/composite-installer_move_as_standard?expand=1
  - move scripts into "Zenject/source/..."
  - move tests and assets for them into "Zenject/OptionalExtras/IntegrationTests/..."
  - delete asmdef files for CompositeInstallers

2021-02-07 09:40 UTC, Mathijs-Bakker commented
> Is it ok to move them like this?
>   
>   * move scripts into "Zenject/source/..."
>   * move tests and assets for them into "Zenject/OptionalExtras/IntegrationTests/..."
>   * delete asmdef files for CompositeInstallers

Yes exactly.
You have put everything in the correct paths.

2021-02-07 10:47 UTC, tsgcpp commented
@Mathijs-Bakker OK, I've moved composite installers and their tests.
Could you please confirm my new commits?

2021-02-07 11:27 UTC, Mathijs-Bakker approved these changes

2021-02-07 11:29 UTC, Mathijs-Bakker approved these changes

2021-02-07 12:46 UTC, Mathijs-Bakker requested changes
Cool, 
Now we decided to move this feat to Zenject's core we also want to rearrange the ``CompositeScriptableObjectInstaller`` menu item from Installers to Zenject. 

<img width="465" alt="Schermafbeelding 2021-02-07 om 12 43 12" src="https://user-images.githubusercontent.com/7645831/107146285-656a6c80-6947-11eb-8c94-d4d5707d62c0.png">

This menu is generated in ``Zenject/Source/Editor/ZenMenuItems.cs``.
Where we can add something like:
```cs
[MenuItem("Assets/Create/Zenject/Composite Scriptable Object Installer", false, 1)]
        public static void CreateCompositeScriptableObjectInstaller()
        {
            AddCSharpClassTemplate("Composite Scriptable Object Installer", "UntitledInstaller",
                  "using UnityEngine;"
                + "\nusing Zenject;"
                // -->
        }
```
For a better UX it make sense to reorder the Installer section.
So it reads like this:
- Installer
- Mono Installer
- Scriptable Object Installer
- Composite Scriptable Object Installer
        
May I ask you to take care of this?
Drop me a line for any help.

Cheers!

2021-02-07 12:46 UTC, Mathijs-Bakker commented on Documentation/CompositeInstaller.md
> +<!-- END doctoc generated TOC please keep comment here to allow auto update -->
This piece of code is generated by a GitHub action. (DocToc)
These lines (1 to 14) can be moved to to under the ``## Table Of Contents`` header without causing any issues.

2021-02-07 12:46 UTC, Mathijs-Bakker commented on Documentation/CompositeInstaller.md
> +
Line 19 and 20 can be removed.
When the DocToc generated lines are moved to here.

2021-02-07 12:46 UTC, Mathijs-Bakker commented on UnityProject/Assets/Plugins/Zenject/Source/Install/CompositeScriptableObjectInstaller.cs
> +    [CreateAssetMenu(fileName = "CompositeScriptableObjectInstaller", menuName = "Installers/CompositeScriptableObjectInstaller")]
This ``CreateAssetMenu`` line can be removed 
after a new ``[MenuItem("Assets/Create/Zenject/...]`` is created (in Editor/ZenMenuItems.cs)

2021-02-07 15:13 UTC, tsgcpp commented
@Mathijs-Bakker Now, I'm editing "ZenMenuItems".

![screenshot 2021-02-07 234750](https://user-images.githubusercontent.com/19503967/107150043-2ff16d80-699f-11eb-8061-5c677a3be8e7.jpg)

I have a question.
Should I add a separator between other installers and "Composite Scriptable Object Installer" like this?

![image](https://user-images.githubusercontent.com/19503967/107150578-c030b200-69a1-11eb-9a7a-917053e064af.png)

`Installer`, `Mono Installer`, `Scriptable Object Installer` will create a "script" file, but "Composite Scriptable Object Installer" will create an "asset" file of "CompositeScriptableObjectInstaller".

Would you give me your opinion?

## WIP diff
https://github.com/tsgcpp/Extenject/compare/feature/composite-installer...tsgcpp:wip/feature/composite-installer?expand=1

2021-02-07 15:23 UTC, Mathijs-Bakker commented
> @Mathijs-Bakker Now, I'm editing "ZenMenuItems".
> 
> ![screenshot 2021-02-07 234750](https://user-images.githubusercontent.com/19503967/107150043-2ff16d80-699f-11eb-8061-5c677a3be8e7.jpg)
> 
> I have a question.
> Should I add a separator between other installers and "Composite Scriptable Object Installer" like this?
> 
> ![image](https://user-images.githubusercontent.com/19503967/107150578-c030b200-69a1-11eb-9a7a-917053e064af.png)
> 

Without the line separator looks the cleanest.

That was also my initial concern to reverse the order of the installers. 
- Installer
- Mono Installer
- Scriptable Object Installer
- Composite Scriptable Object Installer
It is clearer for the user to grasp the differences between the installers. Don't you think?

2021-02-07 15:38 UTC, tsgcpp commented
@Mathijs-Bakker Thank you for your opinion.

> It is clearer for the user to grasp the differences between the installers. Don't you think?

Yes, I think so.
OK, I will edit like this:
![screenshot 2021-02-07 234750](https://user-images.githubusercontent.com/19503967/107150043-2ff16d80-699f-11eb-8061-5c677a3be8e7.jpg)

Could you wait for a few days?
I will complete it and fix the document.

2021-02-07 15:42 UTC, Mathijs-Bakker commented
> Could you wait for a few days?
> I will complete it and fix the document.

No worries!
Take your time!

2021-02-08 13:31 UTC, tsgcpp commented
@Mathijs-Bakker I've added  a menu item "Composite Scriptable Object Installer" and fixed "Table Of Contents" of "CompositeInstaller.md".

I also edited "UnityInspectorListEditor" to warn circular references in any contexts like this (not pushed yet):
![image](https://user-images.githubusercontent.com/19503967/107225278-f3377c00-6a5b-11eb-8722-5b884202caae.png)

Should I push this ([diff](https://github.com/tsgcpp/Extenject/compare/14e5750...fbc3f3c?expand=1))?

2021-02-08 20:24 UTC, Mathijs-Bakker commented
Yeah, you can push this diff to this pr.
Then we have everything in place. @tsgcpp 
👍

2021-02-09 13:00 UTC, tsgcpp commented
@Mathijs-Bakker I've pushed the diff.
Could you please confirm new commits?

2021-02-09 13:09 UTC, tsgcpp commented
@Mathijs-Bakker 
I'm sorry. Can you give me more time.
It seems that there is a bug when Extenject validation are executed.
Then, Unity freezes.

2021-02-09 13:52 UTC, tsgcpp commented
I found the cause of the bug.
If there is a circular references in any composite installers, "StackOverflowException" is not sometimes thrown and Unity is terminated.
I should have added a validation to composite installers before their "InstallBindings"...

I will push new commits to fix that when it is resolved.

2021-02-11 02:33 UTC, tsgcpp commented
OK, I've resolved the bug and added assertions to composite installers before "InstallBindings" of their leaves.
If any circular references are found in composite installers, "ZenjectException" will be thrown in Runtime and "Zenject -> Validate ...".
I also fixed validation methods to reduce allocations because the validation methods became used in Runtime (No allocations up to 4 chains).

Could you please confirm new commits again? @Mathijs-Bakker

2021-02-11 11:42 UTC, Mathijs-Bakker approved these changes
@tsgcpp
Good! I see you have added the asserts.
Great!

Runned this locally (2019.LTS)... everything behaved as expected. 
Awesome work!

I will merge this pr tomorrow. 

The readme.md needs a reference to the new doc too. And a brief explanation about this feature.
I can append a section to it.

:star: :star: :star: Awesome work! :star: :star: :star:

2021-02-11 23:58 UTC, merged

2021-02-11 23:58 UTC, Mathijs-Bakker commented
Merged.

2021-02-12 12:11 UTC, tsgcpp commented
I really appreciate your supports! @Mathijs-Bakker 
I hope this contribution will help the developers.